import 'dart:math';

/// The app's trash-talk engine: one-liners shown when a player gives
/// up or loses a quest. Tone: playful roast — cheeky, never cruel.
/// Style reference (from the game designer):
///   "Even the loading screen showed more commitment."
///   "That was embarrassing."
///   "Well... that escalated into failure."
abstract class Roasts {
  static final _random = Random();

  /// A random roast — the whole point is never seeing the same one twice.
  static String random() => lines[_random.nextInt(lines.length)];

  static const List<String> lines = [
    // ── Commitment jabs ─────────────────────────────────────
    'Even the loading screen showed more commitment.',
    'That was embarrassing.',
    'Well... that escalated into failure.',
    'Your commitment lasted shorter than a free trial.',
    'The tutorial believed in you. The tutorial was wrong.',
    'Even your phone battery lasts longer than your motivation.',
    'Quitting speedrun: new personal best.',
    'Your discipline just rage-quit before you did.',
    'The couch won. Again.',
    'Somewhere, a participation trophy just revoked itself.',
    'Your streak called. It wants a better owner.',
    'Commitment level: airplane mode.',
    'You had ONE job. Zero of it got done.',
    'The snooze button is writing your biography now.',
    'Your habits filed for divorce.',
    'Impressive. Most people at least pretend to try.',
    'The quest is not mad, just disappointed. We are mad.',
    'You folded faster than cheap lawn furniture.',
    'Your willpower left on read.',
    'History will remember this. Unfortunately.',
    'That effort could fit in a single pixel.',
    'You brought a nap to a habit fight.',
    'Your future self just facepalmed.',
    'Even autocorrect saw this coming.',
    'Achievement unlocked: Nothing.',
    'The bar was on the floor. You brought a shovel.',
    'Your aura just asked for witness protection.',
    'Consistency called in sick. Permanently.',
    'That was a masterclass in giving up.',
    'You turned potential into a cautionary tale.',
    // ── Gaming / tech flavored ──────────────────────────────
    'Skill issue. Habit issue, technically.',
    'You got outplayed by a calendar.',
    'Respawn timer: your motivation. ETA: unknown.',
    'Error 404: discipline not found.',
    'You just speedran disappointment any%.',
    'Game over. Insert effort to continue.',
    'Your character build maxed out excuses.',
    'You lost to an NPC called Monday.',
    'Lag is not an excuse in real life.',
    'Uninstalling your dedication... 100% complete.',
    'The final boss was a to-do list. It won.',
    'You picked easy mode and still wiped.',
    'Your save file is just regrets now.',
    'AFK from your own life. Bold strategy.',
    'The dice had more spine than you today.',
    'Critical fail. No reroll available.',
    'You aggroed failure and it one-shot you.',
    'Patch notes: nerfed your own future.',
    'Your loot this run: shame, x1.',
    'Spectator mode suits you.',
    'You farmed excuses instead of aura.',
    'Combo breaker: your own bed.',
    'Your K/D ratio against habits is unspeakable.',
    'Loading excuses… this may take a while.',
    'You died to the tutorial boss of adulthood.',
    'Controller disconnected. So did your ambition.',
    'That run was a cutscene of surrender.',
    'The leaderboard just breathed a sigh of relief.',
    'You minmaxed mediocrity.',
    'Alt+F4 is not a life strategy.',
    // ── Dry observations ────────────────────────────────────
    'Statistically, someone had to be this person. Congrats.',
    'The good news: it cannot get worse. Probably.',
    'This is why we cannot have nice streaks.',
    'Your excuses are more consistent than your habits.',
    'Somewhere a motivational poster just caught fire.',
    'Rome was not built in a day. You did not even show up.',
    'The early bird saw you sleeping and left.',
    'Your comfort zone sends warm regards.',
    'Gravity pulls harder on quitters. Science, probably.',
    'A for effort? More like absent for effort.',
    'You made procrastination look athletic.',
    'The definition of insanity is... whatever this was.',
    'Your potential is writing a missing person report.',
    'Today\'s forecast: 100% chance of nope.',
    'Even Mondays feel sorry for you now.',
    'You just donated your aura to the void.',
    'The void says thanks, by the way.',
    'Legends never die. You were never at risk.',
    'Your ancestors survived ice ages. You lost to a checkbox.',
    'The checkbox remains unbeaten.',
    'That was almost something. Almost.',
    'We ran the numbers. They ran away.',
    'Your grind has left the chat.',
    'This performance has been rated E for Empty.',
    'A moment of silence for your streak. ...Moving on.',
    'The universe is expanding. Your effort is not.',
    'You had momentum once. It filed a restraining order.',
    'Breaking news: local hero takes day off from heroism. Forever.',
    'Your habit tracker is now a disappointment tracker.',
    'At least the app got some exercise closing this quest.',
    // ── Fake encouragement ──────────────────────────────────
    'On the bright side: lowered expectations are easier to meet.',
    'Look at you, pioneering new ways to not do things.',
    'Great job showing that quest who is not the boss.',
    'Ten out of ten quitting form. Judges are weeping.',
    'You are not a failure. This, however, was a failure.',
    'Do not think of it as losing. Think of it as... no, it is losing.',
    'Every master was once a disaster. You nailed phase one.',
    'Believe in yourself! Someone has to.',
    'You miss 100% of the check-ins you do not take. And did.',
    'Failure is the best teacher. You are its favorite student.',
    'Tomorrow is a new day to also not do this.',
    'Your comeback story just got a great origin chapter.',
    'Think positive: your bed clearly loves you.',
    'What does not kill your streak... oh wait, it did.',
    'Congratulations on your consistency. At quitting.',
    'You gave it your some.',
    'Practice makes perfect. Absence makes this.',
    'Chin up. The floor has seen worse. Barely.',
    'You are the main character. Of a tragedy.',
    'Growth mindset activated: growing excuses.',
    // ── Aura-specific burns ─────────────────────────────────
    'Your aura is now a cautionary whisper.',
    'Aura status: visible only under a microscope.',
    'You had aura. Past tense. Learn from the grammar.',
    'The shop will miss your impulse purchases.',
    'Your aura went to buy milk and never came back.',
    'Negative aura is not a vibe. It is a lifestyle now.',
    'Even the Streak Shield could not shield this decision.',
    'Aura does not grow on quitters.',
    'Your glow just got repossessed.',
    'The pot took your aura. Custody battle: lost.',
    'Aura update: gone. Reason: you.',
    'Your energy could not even power the loading spinner.',
    // ── Short and brutal ────────────────────────────────────
    'Oof.',
    'Yikes.',
    'Bold. Wrong, but bold.',
    'That happened.',
    'Noted. Judged. Archived.',
    'The dice saw everything.',
    'We all saw that.',
    'Delete your excuses.',
    'Painful to watch. We watched anyway.',
    'A new low. Impressive depth.',
    'This will be on your permanent record.',
    'Somewhere, your gym membership laughed.',
    'Blink twice if your motivation is held hostage.',
    'The quest deserved better. So did you. Awkward.',
    'Filed under: things we do not talk about.',
    'Your discipline is now a myth. Like dragons.',
    'This is fine. (It is not fine.)',
    'Take a bow. Then take a long look in the mirror.',
    'The algorithm of failure has accepted your submission.',
    'Even this message tried harder than you did.',
  ];
}
