import 'dart:math';

/// A database of 300 savage, demotivating, cheeky English youth & gaming roasts
/// designed for targeted player roast attacks in Aura Quest.
abstract class Roasts300 {
  static final _random = Random();

  /// Returns 3 distinct random roasts from the 300-roast database.
  static List<String> drawThree() {
    final copy = List<String>.from(lines)..shuffle(_random);
    return copy.take(3).toList();
  }

  /// Get a single random roast.
  static String random() => lines[_random.nextInt(lines.length)];

  static const List<String> lines = [
    // ── 1-50: Gaming & Tech Trash Talk ────────────────────────
    'Skill issue. Not even on easy mode could you get your life together.',
    'Even the tutorial boss had more respect for your time than you did.',
    'Main character syndrome with background NPC energy.',
    'Go touch grass. Honestly, the couch is getting worried about you.',
    'You speedran disappointment any% without taking a single breather.',
    'You had one job. You did not even load into the game.',
    'Your discipline just rage-quit and uninstalled itself.',
    'Error 404: Willpower not found in local system files.',
    'Statistically, someone had to be this lost. Congrats on taking the trophy.',
    'Even your phone battery has more stamina than your streak.',
    'AFK from your own goals. Bold strategy, let us see how it plays out.',
    'You got outplayed by a calendar app. Truly tragic.',
    'Respawn timer for your motivation: Estimated arrival... never.',
    'Your character build maxed out excuses and dumped discipline.',
    'You picked easy mode and still managed to wipe the party.',
    'Controller disconnected? No, your ambition just gave up.',
    'Lag is not an excuse when you are standing still in real life.',
    'Uninstalling your dedication... 100% complete.',
    'The final boss was a single daily habit. It won in one hit.',
    'Your save file is 90% regrets and 10% unfulfilled promises.',
    'You aggroed failure and got one-shot before the cutscene ended.',
    'Patch notes: Nerfed your consistency down to zero.',
    'Your loot for this run: Pure embarrassment, x1.',
    'Spectator mode suits your work ethic perfectly.',
    'You farmed excuses all day instead of stacking aura.',
    'Combo breaker: Your own bed.',
    'Your K/D ratio against basic responsibilities is unspeakable.',
    'Loading excuses… Please wait while your potential evaporates.',
    'You died to the tutorial boss of adulthood.',
    'Alt+F4 is not a valid habit-building strategy.',
    'You minmaxed mediocrity and achieved absolute zero.',
    'The leaderboard breathed a collective sigh of relief when you quit.',
    'Critical fail. No reroll available for this level of effort.',
    'You brought a nap to a grinding session.',
    'Your Wi-Fi might be fast, but your progress is stuck on dial-up.',
    'Even an NPC villager in Minecraft shows more initiative.',
    'You are running on 1% battery and zero motivation.',
    'Your character stats: Strength 0, Stamina 0, Excuses 99.',
    'You got spawnkilled by a Monday morning.',
    'Ping to success: 9999ms. Connection timed out.',
    'Your motivation crashed without producing an error dump.',
    'You fell into a pitfall trap that was clearly marked with a sign.',
    'Your quest log is just a collection of abandoned dreams.',
    'You tried to cheese the quest and ended up outplaying yourself.',
    'Graphics set to Ultra, effort set to Lowest Possible.',
    'You are spectating life from the bench of excuses.',
    'Even a broken bot achieves a random victory once in a while.',
    'Your streak called in sick and filed for retirement.',
    'System overload: Excuses exceeded storage limit.',
    'Game over. Insert actual effort to continue.',

    // ── 51-100: Habit & Discipline Disasters ──────────────────
    'Your couch misses you when you stand up for ten seconds.',
    'Discipline? You probably think that is a brand of mineral water.',
    'You are the undefeated champion of giving up early.',
    'Your desk chair has logged more miles than your running shoes.',
    'Folding faster than cheap lawn furniture in a hurricane.',
    'Your bed is your only loyal partner in life right now.',
    'Your excuses have officially earned a spot on the bestseller list.',
    'You talked like a achiever, but your tracker screams couch potato.',
    'You did not even try to hold the line.',
    'Even a snail on sleeping pills would pass you on the trail.',
    'Your inner sloth didn\'t just defeat you, it rules your kingdom.',
    'Collapsing faster than a house of cards in a breeze.',
    'If laziness burned calories, you would be skin and bones.',
    'Your excuses are getting embarrassing for everyone involved.',
    'You are an autopilot system programed to crash into the nearest wall.',
    'Even the snooze button shows more commitment to its job.',
    'Your discipline dissolved the moment mild discomfort appeared.',
    'You cannot even get up when the Wi-Fi drops.',
    'Your daily habits look like an abandoned construction site.',
    'You practiced giving up until you turned it into a fine art.',
    'Even in your sleep you contribute more than during your waking hours.',
    'Your focus has the attention span of a goldfish on caffeine.',
    'You fold under pressure like a wet paper towel.',
    'Your discipline went on vacation and forgot to leave a return date.',
    'Permanently locked in chill mode without a release date.',
    'If inconsistency was an academic subject, you would graduate with honors.',
    'You aimed for the stars and tripped over a flat rug.',
    'Even a stationary rock shows more dynamic energy.',
    'Your resolutions expire faster than an Instagram story.',
    'You are the living embodiment of zero momentum.',
    'Your comfort zone put a leash on you and takes you for walks.',
    'You outdid yourself today — in finding reasons to quit.',
    'Your stamina lasts exactly until the next snack break.',
    'You are like a car with no engine: Only moves downhill.',
    'Your convenience is your own worst enemy.',
    'Gravity seems to push harder on quitters. Science, probably.',
    'You turn tiny molehills into ironclad excuses to stop.',
    'Your motivation is like a ghost: Frequently mentioned, never seen.',
    'Please just go back to sleep, the world is easier that way.',
    'The bar was on the floor and you brought a shovel to dig under it.',
    'You are the poster child for "I will start tomorrow."',
    'You took laziness and elevated it to a high art form.',
    'Your daily report card is a sea of red red ink.',
    'Deflated like a birthday balloon three weeks after the party.',
    'Your consistency is like a colander: Holds absolutely nothing.',
    'Even the dust on your desk gets moved around more than you.',
    'You snap under the lightest gust of effort.',
    'Your mindset is desperately waiting for a software update.',
    'You are simply, unequivocally, completely lost.',

    // ── 101-150: Main Character & Ego Checks ──────────────────
    'Main character syndrome with background extras performance.',
    'You talked a big game, but delivered a microscopic result.',
    'Your expectations and your work ethic live on different planets.',
    'You wanted to conquer the day and could not even make your bed.',
    'Self-awareness: 100%. Actual execution: 0%.',
    'You are the protagonist of a slow-motion comedy of errors.',
    'Your announcements are like hype trailers: All CGI, zero gameplay.',
    'Promised a flex, delivered a sad collapse.',
    'Your ego takes up two seats, but your results fit in a thimble.',
    'You act like the boss, but cannot manage the basic tasks.',
    'Your talk is ironclad, your execution is wet cardboard.',
    'You tried to fly and tripped over the curb before takeoff.',
    'Your self-assessment is a pure hallucination.',
    'Big dreams, microscopic hustle.',
    'Posted "Sigma Mindset" and tapped out five minutes later.',
    'Your ego has its own ZIP code; your discipline is homeless.',
    'You brag about victories that only happened in your head.',
    'You are the trailer version of success: Sounds cool, zero substance.',
    'Even your daydreams are shaking their heads at you.',
    'You bit off more than you could chew and choked on air.',
    'Tried to reach for the stars and stubbed your toe on the couch.',
    'Your social media is hype, your reality is a quiet surrender.',
    'The undisputed master of loud announcements and silent quits.',
    'You think you are a genius, but the data says otherwise.',
    'Your confidence is wildly unearned.',
    'Spoke loud in the group chat, went missing on the leaderboard.',
    'Your ambitions are like soap bubbles: Pop on contact.',
    'Dressed up for victory, showed up for defeat.',
    'Your main character license has been permanently revoked.',
    'Wanted to write history, only managed to produce junk.',
    'Your vision is massive; your effort is invisible.',
    'You are a cheap knockoff of your own potential.',
    'Talks like a winner, acts like a professional dodger.',
    'Your excuses have far more polish than your actual work.',
    'Wanted to make an impression, only managed to cause pity.',
    'Your output is wildly out of proportion with your mouth.',
    'Hero of your own story — unfortunately, the story is fiction.',
    'Your quotes sound deep, your actions look silly.',
    'Wanted to reach the top and did not even tie your shoes.',
    'Your self-image needs a strong prescription pair of glasses.',
    'Grand strategy, zero tactical stamina.',
    'Wanted to shine and ended up rusting instead.',
    'Your hype melts faster than ice cream in August.',
    'Undefeated monarch of empty promises.',
    'Talked big in the morning, went radio silent by noon.',
    'Your ego needed a reality check, and here it is.',
    'Star of a solo show that nobody bought tickets for.',
    'Stop dreaming out loud and start delivering in silence.',

    // ── 151-200: Aura & Vibe Deficits ─────────────────────────
    'Your aura dropped into negative interest rates today.',
    'You have the magnetic aura of a plastic grocery bag in the wind.',
    'Minus 10,000 aura for that breathtakingly bad performance.',
    'Your vibe is so rancid today, indoor plants are wilting.',
    'Your aura officially filed for Chapter 11 bankruptcy.',
    'You do not even have micro-aura left. Completely drained.',
    'Your aura radiates the gloomy energy of a rainy Monday.',
    'Completed the negative aura speedrun. Congrats on the record.',
    'Your aura packed its bags and left without leaving a note.',
    'Even a shadow has more presence than you brought today.',
    'You emit the high-voltage energy of a unplugged toaster.',
    'Your aura is absolute zero: A physical void of nothingness.',
    'You have so little vibe we could use you as a mannequin.',
    'The Aura Police revoked your license due to severe disappointment.',
    'Your aura is currently applying for government assistance.',
    'No vibe, no aura, no progress. The holy trinity of taking an L.',
    'Your presence makes the room feel slightly colder and sadder.',
    'You accumulated so much negative aura it will take weeks to clear.',
    'Your vibe check returned a counterfeit verdict.',
    'Zero charisma, zero discipline. Just a quiet tragedy.',
    'Your aura is stuck on Windows 95 safe mode.',
    'Radiating less confidence than a flickering candle in a hurricane.',
    'Your aura is a ghost ship: Abandoned, drifting, and sunk.',
    'Your own aura sued you for emotional damage.',
    'Even a turnip brings more charm to the table than you did.',
    'Harvested negative aura for the ages today.',
    'Your presence today is second-hand embarrassment personified.',
    'Your vibe is so negative it actively repels success.',
    'Your aura is worth less than an expired coupon.',
    'You are an aura vampire — draining the room\'s morale.',
    'No glow, no flex, just a dark stain on the leaderboard.',
    'Your aura switch was accidentally set to standby mode.',
    'Your energy reserves hit an all-time low today.',
    'You have the glowing aura of a burnt-out lightbulb.',
    'Your vibe is screaming "I gave up before I started."',
    'Your aura just submitted an eviction notice to your body.',
    'Your radiance is as dry as the Sahara desert.',
    'Not even a 4K filter could make your performance look good.',
    'Your aura evaporated faster than water on a hot skillet.',
    'Living proof against the concept of "good vibes only."',
    'Your presence is a tragic one-man play.',
    'Your aura quietly slipped out the back door while you slept.',
    'No style, no flex, just pure unfiltered surrender.',
    'Your aura is a dead zone: Zero bars, zero service.',
    'You are dragging down the average aura of the entire team.',
    'Your aura output today: An absolute disaster.',
    'Your aura could not even produce a faint glimmer.',
    'Your vibes today are subterranean.',
    'Your aura bank account is severely overdrawn.',
    'Recharge your aura please. This is getting painful to watch.',

    // ── 201-250: Social & Daily Life Sarcasm ──────────────────
    'Massive L-take on life today. Just go back to bed, bro.',
    'Your friends are secretly hiding your habit stats from public view.',
    'Even stray pets look at you with deep, genuine concern.',
    'Your calendar is weeping softly in the background.',
    'You cannot even throw dirty socks into the hamper successfully.',
    'Everyone in the room knows your excuses by heart now.',
    'The local garbage pickup schedule has more structure than your day.',
    'You are a walking tutorial on how NOT to do things.',
    'Your productivity stats are currently frozen solid.',
    'Your performance today was one continuous cringe moment.',
    'Please go outside and apologize to a tree for wasting its oxygen.',
    'Even your coffee maker shows more daily drive than you.',
    'Your new year resolutions are already sitting in a landfill.',
    'You set the bar so low people are tripping over it in the dark.',
    'Your daily routine looks like a pile of unorganized laundry.',
    'Your discipline was banned from the premises.',
    'You are officially the disappointment of the day.',
    'Running on low power mode — minus the actual power.',
    'Go stand in the corner and reflect on this performance.',
    'You did not just lose the thread, you set the spool on fire.',
    'Even your keyboard hesitates before typing your excuses.',
    'Your track record today is darker than a moonless night.',
    'Your contribution to team success: Exactly zero.',
    'You are like a flat tire: Holding everybody back from moving.',
    'Your motivation ran away and joined the circus.',
    'Your effort was a slap in the face to anyone who actually tried.',
    'You are the sole reason group projects take twice as long.',
    'Outdid yourself today in the field of falling short.',
    'Your internal motor is completely rusted shut.',
    'Please pack up your things and take a long nap.',
    'Your excuses are ten out of ten on the ridiculous scale.',
    'Even your own shadow looks ashamed to be attached to you.',
    'Officially inducted into the Laziness Hall of Fame.',
    'Your results speak volumes — tragic, depressing volumes.',
    'Your effort today was an absolute joke without a punchline.',
    'Completely lost the plot three sentences into the chapter.',
    'Your sluggishness is contagious, please step back.',
    'Even the algorithm is recommending you get some discipline.',
    'Congratulations on carrying the red lantern of defeat today.',
    'Your performance was below all acceptable standards.',
    'Your habit score is currently residing in the basement.',
    'Broke your word to yourself for the third time before lunch.',
    'Grandmaster of hot air and empty gestures.',
    'Even a garden snail is doing laps around your progress.',
    'Your excuses do not work on anyone anymore.',
    'Failed with 100% confidence and zero hesitation.',
    'Your output today is genuinely heartbreaking.',
    'Stand up, dust yourself off, and try actually caring.',
    'That was the most painful display of the entire week. Oof.',
    'You brought a white flag to a daily check-in.',

    // ── 251-300: Brutal One-Liners & Savage Observations ─────
    'Oof. That was hard to watch.',
    'Yikes. Even the app felt that one.',
    'Bold strategy to fail so publicly.',
    'That happened. Unfortunately for everyone.',
    'Noted. Judged. Archived into the hall of shame.',
    'The leaderboard saw everything and is unimpressed.',
    'We all witnessed that collapse in real time.',
    'Delete your excuses and try again.',
    'Painful to observe. We observed it anyway.',
    'A new low! Impressive depth, honestly.',
    'This L will stay on your permanent record.',
    'Somewhere, your gym membership just giggled.',
    'Blink twice if your motivation is being held hostage.',
    'The quest deserved better. So did your team.',
    'Filed directly under: Things we pretend never happened.',
    'Your discipline is now a mythical creature. Like dragons.',
    'This is fine. (Spoiler: It is absolutely not fine.)',
    'Take a bow. Then take a long, hard look in the mirror.',
    'The algorithm of failure accepted your submission instantly.',
    'Even this notification tried harder than you did today.',
    'Zero effort detected by sensor array.',
    'You put the "less" in effortless.',
    'A moment of silence for your streak. Moving on.',
    'Your comeback story is stuck in pre-production.',
    'You brought negative energy to a positive space.',
    'Participation trophy revoked.',
    'Your discipline ghosted you.',
    'You folded faster than an origami crane.',
    'Achievement unlocked: Absolutely Nothing.',
    'You turned gold into dust.',
    'Your motivation expired yesterday.',
    'Your habit tracker is crying in the corner.',
    'You fell off. Hard.',
    'Ratio + L + No discipline.',
    'Fraud alert triggered on your habit card.',
    'You are spectating your own goals.',
    'Zero stars. Would not recommend your work ethic.',
    'You turned a small task into a major crisis.',
    'Your grind set is permanently on pause.',
    'You gave 1% and expected 100% results.',
    'Your effort was lost in transit.',
    'You got benched by your own habits.',
    'Your discipline is currently unassigned.',
    'You traded progress for five more minutes of sleep.',
    'Your streak was short-lived and quickly forgotten.',
    'You reached the bottom and started digging.',
    'Your effort was rated E for Empty.',
    'You brought excuses to a stat fight.',
    'Your progress bar went backwards.',
    'That performance was a total blackout.',
  ];
}
